# Generated by Django 4.0.4 on 2022-06-05 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monedas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dolar',
            name='nombre',
            field=models.CharField(default='Dolar', max_length=50),
        ),
        migrations.AddField(
            model_name='dolar_blue',
            name='nombre',
            field=models.CharField(default='Dolar Blue', max_length=50),
        ),
        migrations.AddField(
            model_name='euro',
            name='nombre',
            field=models.CharField(default='Euro', max_length=50),
        ),
        migrations.AddField(
            model_name='reais',
            name='nombre',
            field=models.CharField(default='Real', max_length=50),
        ),
    ]
